### ISSUE TITLE
Hoàn thành selenium test case - P1

### ISSUE THREAD

**Issue by KhaiNguyenDuc** [KhaiNguyenDuc/Nhom01-DeTai01-Label-Studio#102]
- [x] Webhook
- [x] Project
- [x] Organization
- [x] Cloud Storage
- [x] User

**Comment by NguyenDucThinhIT** [comment]
Task 18/04/2023: Hoàn thành test case Webhook

**Comment by NguyenDucThinhIT** [comment]
Đã hoàn thành test 
Link minh chứng:

**Comment by NguyenDucThinhIT** [comment]
Task 18/04/2023: Hoàn thành test case Project Part 1

**Comment by NguyenDucThinhIT** [comment]
Đã hoàn thành test
Link minh chứng:

**Comment by NguyenDucThinhIT** [comment]
Task 18/04/2023: Hoàn thành test case Project Part 2

**Comment by NguyenDucThinhIT** [comment]
Đã hoàn thành test
Link minh chứng:

**Comment by NguyenDucThinhIT** [comment]
Task 18/04/2023: Hoàn thành test case Organization Part 1

**Comment by NguyenDucThinhIT** [comment]
Đã hoàn thành test
Link minh chứng:

**Comment by NguyenDucThinhIT** [comment]
Task 18/04/2023: Hoàn thành test case Organization Part 2

**Comment by NguyenDucThinhIT** [comment]
Đã hoàn thành test
Link minh chứng:

**Comment by NguyenDucThinhIT** [comment]
Task 18/04/2023: Hoàn thành test case Cloud Storage Part 1

**Comment by NguyenDucThinhIT** [comment]
Đã hoàn thành test
Link minh chứng:

**Comment by NguyenDucThinhIT** [comment]
Task 24/04/2023: Hoàn thành test case Cloud Storage Part 2

**Comment by NguyenDucThinhIT** [comment]
Đã hoàn thành test
Link minh chứng:

**Comment by NguyenDucThinhIT** [comment]
Task 24/04/2023: Hoàn thành test case User

**Comment by NguyenDucThinhIT** [comment]
Đã hoàn thành test
Link minh chứng:
