### ISSUE TITLE
Hoàn thành test case - P2 

### ISSUE THREAD

**Issue by KhaiNguyenDuc** [KhaiNguyenDuc/Nhom01-DeTai01-Label-Studio#103]
- [x] Label interface
- [x] Invite
- [x] Instruction
- [x] Import Data
- [x] Export Data

**Comment by kiet2709** [comment]
Ngày 18/4/2023: hoàn thành một phần test Label Interface
  + test_create_label_xml
  + test_select_template
Link minh chứng: https://github.com/KhaiNguyenDuc/Nhom01-DeTai01-Label-Studio/blob/main/test-label-studio/label_interface/test_label.py

**Comment by kiet2709** [comment]
Ngày 19/4/2023: hoàn thành test Label Interface:
   + test_create_label_GUI
   + test_config_label_color
Link minh chứng: https://github.com/KhaiNguyenDuc/Nhom01-DeTai01-Label-Studio/blob/main/test-label-studio/label_interface/test_label.py

**Comment by kiet2709** [comment]
Ngày 20/4/2023: hoàn thành test Invite và Instruction:
   + test_invite
   + test_add_instruction
Link minh chứng: 
   + https://github.com/KhaiNguyenDuc/Nhom01-DeTai01-Label-Studio/blob/main/test-label-studio/invite/test_invite.py
   + https://github.com/KhaiNguyenDuc/Nhom01-DeTai01-Label-Studio/blob/main/test-label-studio/instruction/test_instruction.py

**Comment by kiet2709** [comment]
Ngày 21/4/2023: hoàn thành test Import Data:
   + test_import__dataset_url
   + test_import__upload_files
Link minh chứng: https://github.com/KhaiNguyenDuc/Nhom01-DeTai01-Label-Studio/blob/main/test-label-studio/import_data/test_import_data.py

**Comment by kiet2709** [comment]
Ngày 22/4/2023: hoàn thành một phần test Label Interface:
   + test_export_json
   + test_export_json_min
Link minh chứng: https://github.com/KhaiNguyenDuc/Nhom01-DeTai01-Label-Studio/blob/main/test-label-studio/export_data/test_export_data.py

**Comment by kiet2709** [comment]
Ngày 23/4/2023: hoàn thành một phần test Export Data:
    + test_export_csv
    + test_export_tsv
Link minh chứng: https://github.com/KhaiNguyenDuc/Nhom01-DeTai01-Label-Studio/blob/main/test-label-studio/export_data/test_export_data.py

**Comment by kiet2709** [comment]
Ngày 22/4/2023: hoàn thành test Export Data:
   + test_export_coco
Link minh chứng: https://github.com/KhaiNguyenDuc/Nhom01-DeTai01-Label-Studio/blob/main/test-label-studio/export_data/test_export_data.py
