### ISSUE TITLE
18/03/2023: Tìm hiểu documentation - machine learning của đề tài mẫu 

### ISSUE THREAD

**Issue by KhaiNguyenDuc** [KhaiNguyenDuc/Nhom01-DeTai01-Label-Studio#14]
+ Machine learning integration
+ Write your own ML backend

**Comment by kiet2709** [comment]
Hoàn thành
Tài liệu: https://docs.google.com/document/d/1vqrKRRa4HDSmAABA9dqPmHqP-GjHwAbZ/edit?usp=sharing&ouid=112692646401533875846&rtpof=true&sd=true
