### ISSUE TITLE
18/03/2023: Tìm hiểu documentation - frontend buid & frontend của đề tài mẫu

### ISSUE THREAD

**Issue by KhaiNguyenDuc** [KhaiNguyenDuc/Nhom01-DeTai01-Label-Studio#16]

**Comment by NguyenDucThinhIT** [comment]
đã hoàn thành task 4
link Doc: https://docs.google.com/document/d/1Re43EluvDyOwS8cnxdGmLDTNo2j2f0pZ/edit?usp=share_link&ouid=105379913189626044942&rtpof=true&sd=true
