### ISSUE TITLE
19/03/2023: Tìm hiểu docker và môi trường cài đặt đề tài mẫu 

### ISSUE THREAD

**Issue by KhaiNguyenDuc** [KhaiNguyenDuc/Nhom01-DeTai01-Label-Studio#17]

**Comment by kiet2709** [comment]
Hoàn thành
Tài liệu: https://docs.google.com/document/d/1fWqyOSpc90ZxdSwxyv86esCY1OWSKbna/edit?usp=sharing&ouid=112692646401533875846&rtpof=true&sd=true
