### ISSUE TITLE
Tìm hiểu postgresql cho đề tài mẫu 

### ISSUE THREAD

**Issue by KhaiNguyenDuc** [KhaiNguyenDuc/Nhom01-DeTai01-Label-Studio#24]

**Comment by NguyenDucThinhIT** [comment]
đã hoàn thành xong task 7
link doc: https://docs.google.com/document/d/15H9hs22SqwBVHYVDqEWoLCmr_XU_i9Wv/edit?usp=share_link&ouid=105379913189626044942&rtpof=true&sd=true
