### ISSUE TITLE
Tìm hiểu AWS cho đề tài mẫu 

### ISSUE THREAD

**Issue by KhaiNguyenDuc** [KhaiNguyenDuc/Nhom01-DeTai01-Label-Studio#25]

**Comment by kiet2709** [comment]
Hoàn thành
Tài liệu: https://docs.google.com/document/d/1fWqyOSpc90ZxdSwxyv86esCY1OWSKbna/edit?usp=sharing&ouid=112692646401533875846&rtpof=true&sd=true
