### ISSUE TITLE
15/03/2023: Tìm hiểu các chức năng của đề tài 

### ISSUE THREAD

**Issue by KhaiNguyenDuc** [KhaiNguyenDuc/Nhom01-DeTai01-Label-Studio#4]

**Comment by kiet2709** [comment]
Hoàn thành
Tài liệu: https://docs.google.com/document/d/1WcnTk7kJp0R6hZsoQwEBD14wbFDlgH60/edit?usp=drive_web&ouid=112692646401533875846&rtpof=true
