### ISSUE TITLE
28/03/2023: SRS Template - Phần 1. Introduction

### ISSUE THREAD

**Issue by KhaiNguyenDuc** [KhaiNguyenDuc/Nhom01-DeTai01-Label-Studio#48]

**Comment by NguyenDucThinhIT** [comment]
đã hoàn thành task
Link minh chứng: https://docs.google.com/document/d/1AQak_ICf1yVxawEPJfxaXe5Vhg_nS7dX/edit?usp=share_link&ouid=103683030096848336921&rtpof=true&sd=true
