### ISSUE TITLE
29/03/2023: SRS Template - Phần 5. Other Nonfunctional Requirements 

### ISSUE THREAD

**Issue by KhaiNguyenDuc** [KhaiNguyenDuc/Nhom01-DeTai01-Label-Studio#52]

**Comment by NguyenDucThinhIT** [comment]
đã hoàn thành task
Link minh chứng: https://docs.google.com/document/d/1v4yjRX8cWE42K0YjchuyJnj8uDcFAvdE/edit?usp=share_link&ouid=103683030096848336921&rtpof=true&sd=true
