### ISSUE TITLE
30/03/202 : Vẽ activity diagram cho: Organization, Invite 

### ISSUE THREAD

**Issue by KhaiNguyenDuc** [KhaiNguyenDuc/Nhom01-DeTai01-Label-Studio#56]

**Comment by NguyenDucThinhIT** [comment]
đã hoàn thành task
Link minh chứng: https://docs.google.com/document/d/1t7VS2q92d-tAFrdSj2_iiPBnuMUHPBeS/edit?usp=share_link&ouid=103683030096848336921&rtpof=true&sd=true
