### ISSUE TITLE
01/04/2023: Vẽ activity diagram cho: Quản lý Task

### ISSUE THREAD

**Issue by KhaiNguyenDuc** [KhaiNguyenDuc/Nhom01-DeTai01-Label-Studio#62]

**Comment by NguyenDucThinhIT** [comment]
đã hoàn thành task
Link minh chứng: https://docs.google.com/document/d/14-817jpfwbW-kzKKeqv14CDg5q3di0BJ/edit?usp=share_link&ouid=103683030096848336921&rtpof=true&sd=true
