### ISSUE TITLE
02/04/2023: Vẽ activity diagram cho AWS S3 storage 

### ISSUE THREAD

**Issue by KhaiNguyenDuc** [KhaiNguyenDuc/Nhom01-DeTai01-Label-Studio#65]

**Comment by NguyenDucThinhIT** [comment]
đã hoàn thành task
Link minh chứng: https://docs.google.com/document/d/13USXZYiXNz24NQkaAlsZlZCvjmP-UKSx/edit?usp=share_link&ouid=103683030096848336921&rtpof=true&sd=true
