### ISSUE TITLE
15/03/2023: Tìm hiểu công nghệ automation test đề tài 

### ISSUE THREAD

**Issue by KhaiNguyenDuc** [KhaiNguyenDuc/Nhom01-DeTai01-Label-Studio#7]

**Comment by NguyenDucThinhIT** [comment]
Đã hoàn thành task 1 
Link doc: https://docs.google.com/document/d/1nH08Vt6nBPRcGHZAHnostcdj81_3lZgT/edit?usp=share_link&ouid=105379913189626044942&rtpof=true&sd=true
