### ISSUE TITLE
03/04/2023: Vẽ activity diagram cho Local storage 

### ISSUE THREAD

**Issue by KhaiNguyenDuc** [KhaiNguyenDuc/Nhom01-DeTai01-Label-Studio#72]

**Comment by NguyenDucThinhIT** [comment]
đã hoàn thành task
Link minh chứng: https://docs.google.com/document/d/1Ku4u43RdlrY0B7ccbhmgpJjpazQrGR_u/edit?usp=share_link&ouid=103683030096848336921&rtpof=true&sd=true
