### ISSUE TITLE
Xây dựng test case - Đăng nhập, đăng ký 

### ISSUE THREAD

**Issue by KhaiNguyenDuc** [KhaiNguyenDuc/Nhom01-DeTai01-Label-Studio#76]
- [x] Đăng nhập 
- [x] Đăng nhập với tài khoản không hợp lệ 
- [x] Đăng ký
- [x] Đăng ký với email không hợp lệ
- [x] Đăng ký với mật khẩu không hợp lệ

**Comment by kiet2709** [comment]
Đã hoàn thành task 6.
Link task đăng nhập: https://github.com/KhaiNguyenDuc/Nhom01-DeTai01-Label-Studio/blob/main/test-label-studio/login/Login.py
Link task đăng ký: https://github.com/KhaiNguyenDuc/Nhom01-DeTai01-Label-Studio/blob/main/test-label-studio/signup/Signup.py

**Comment by kiet2709** [comment]
Đã hoàn thành task 7
Link task đăng ký: https://github.com/KhaiNguyenDuc/Nhom01-DeTai01-Label-Studio/blob/main/test-label-studio/signup/Signup.py
