### ISSUE TITLE
Xây dựng test case - Oragnization, invite 

### ISSUE THREAD

**Issue by KhaiNguyenDuc** [KhaiNguyenDuc/Nhom01-DeTai01-Label-Studio#78]
- [x] Oragnization
- [x] invite

**Comment by NguyenDucThinhIT** [comment]
đã hoàn thành Task 06:
Link minh chứng: https://drive.google.com/file/d/1P7R2MtA_GbnchZQk2V3XpdwXoS52N7jV/view?usp=share_link

**Comment by NguyenDucThinhIT** [comment]
đã hoàn thành Task 07:
Link minh chứng: https://drive.google.com/file/d/1tGZRjKW2DnBNkNAF4kzbBNAw9WrDLUPI/view?usp=share_link
