### ISSUE TITLE
16/03/2023: Chạy thử đề tài mẫu thông qua source code

### ISSUE THREAD

**Issue by KhaiNguyenDuc** [KhaiNguyenDuc/Nhom01-DeTai01-Label-Studio#8]
Link: https://github.com/heartexlabs/label-studio

**Comment by kiet2709** [comment]
Hoàn thành
Tài liệu: https://docs.google.com/document/d/1FejeEgP6iq6vGoDY0PA5fRs8ODs5cL96/edit?usp=sharing&ouid=112692646401533875846&rtpof=true&sd=true
